stages:
  - build
  - deploy

variables:
  IMAGE_NAME: django_api_img
  CON_NAME: django_api_con
  # DOCKER_DRIVER: overlay2
  # DOCKER_TLS_CERTDIR: "/certs"
  # DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  # stage: package
  tags:
    - dev
  image: docker:latest
  services:
    - docker:dind
  script:
    # - "docker login -u \"${CI_REGISTRY_USER}\" -p \"${CI_REGISTRY_PASSWORD}\" \"${CI_REGISTRY}\""
    - cd Django
    - docker container ls -a
    - docker build . -t $IMAGE_NAME
    # - docker push $IMAGE_NAME
    # - docker images | grep '[저장소명]'

deploy:
  stage: deploy
  tags:
    -  dev
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker container ls -a
    - docker container rm -f $CON_NAME
    - docker run -d -p 8000:8000 --name $CON_NAME --restart always $IMAGE_NAME
    - docker container ls -a