# Generated by Django 4.1.6 on 2023-02-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=8, unique=True)),
                ('location', models.CharField(max_length=1)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
            ],
        ),
    ]
