# Generated by Django 4.1.6 on 2023-02-13 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locker_state', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locker',
            old_name='column',
            new_name='col',
        ),
    ]
