# Generated by Django 4.1.6 on 2023-02-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locker_state', '0002_rename_column_locker_col'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locker',
            old_name='col',
            new_name='column',
        ),
    ]
