# Generated by Django 4.1.6 on 2023-02-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker_state', '0003_rename_col_locker_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locker',
            name='id',
        ),
        migrations.AlterField(
            model_name='locker',
            name='studentID',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
