# Generated by Django 4.1.6 on 2023-02-13 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsAuth',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^010?[0-9]\\d{3}?\\d{4}$')], verbose_name='휴대폰 번호')),
                ('auth_number', models.IntegerField(verbose_name='인증 번호')),
            ],
            options={
                'db_table': 'sms_auth',
            },
        ),
        migrations.DeleteModel(
            name='AuthSms',
        ),
    ]
