# Generated by Django 4.1.6 on 2023-02-13 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_delete_smsauth'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
