# Generated by Django 4.1.6 on 2023-02-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='studentID',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
