# Generated by Django 4.1.6 on 2023-02-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_last_login_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cert_table',
            fields=[
                ('phone_num', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('cert_number', models.CharField(max_length=6)),
                ('cert_status', models.BooleanField()),
            ],
        ),
    ]
